sudo: true
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      
script:
 -cmake -H. -B_builds -DCPACK_GENERATO=TGZ
 -cmake --build _builds
 -cmake --build _builds --target package
   
